/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/footer.vue')['default']
    Heropage: typeof import('./src/components/heropage.vue')['default']
    MediaDetails: typeof import('./src/components/pageDetails/mediaDetails.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Populars: typeof import('./src/components/index/populars.vue')['default']
    PopularsSection: typeof import('./src/components/index/popularsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowSearch: typeof import('./src/components/index/showSearch.vue')['default']
  }
}
