/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Heropage: typeof import('./src/components/heropage.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    PopularFilms: typeof import('./src/components/index/popularFilms.vue')['default']
    Populars: typeof import('./src/components/index/populars.vue')['default']
    PopularSeries: typeof import('./src/components/index/popularSeries.vue')['default']
    PopularsSection: typeof import('./src/components/index/popularsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
