export default interface Film {
    backdrop_path: string,
    genre_ids: [],
    genres: [],
    id: number,
    original_language: string,
    overview: string,
    popularity: number,
    poster_path: string,
    release_date: string,
    title ?: string,
    name ?: string,
    vote_average: number,
    vote_count: number,   
    favorite?: boolean,
  }
